default_install_hook_types: [pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        exclude: "(.*\\.(po|pot|svg|ui)$|test/data/.*)"
      - id: end-of-file-fixer
        exclude: "(.*\\.(po|pot|svg|ui)$|test/data/.*)"
      - id: mixed-line-ending
        exclude: "(.*\\.(po|pot|svg|ui)$|test/data/.*)"
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
        exclude: ".*\\.in"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.35
    hooks:
      - id: pymarkdown
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.7
    hooks:
      - id: uv-lock
        name: Sync uv.lock with pyproject.toml
        always_run: true
      - id: pip-compile
        name: pip-compile requirements.txt
        args: [pyproject.toml, -o, requirements.txt, --upgrade, --generate-hashes, --universal, --python-version=3.10]
        files: 'uv.lock'
        stages: [pre-commit]
        pass_filenames: false
      - id: pip-compile
        name: pip-compile requirements-build.txt
        args: [pyproject.toml, -o, requirements-build.txt, --group, build, --upgrade, --generate-hashes, --universal, --python-version=3.10]
        files: 'uv.lock'
        stages: [pre-commit]
        pass_filenames: false
      - id: pip-compile
        name: pip-compile requirements-dev.txt
        args: [pyproject.toml, -o, requirements-dev.txt, --group, dev, --upgrade, --generate-hashes, --universal, --python-version=3.10]
        files: 'uv.lock'
        stages: [pre-commit]
        pass_filenames: false
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: uv run --frozen pytest --numprocesses auto --exitfirst
        language: python
        types: [python]
        stages: [pre-push]
        pass_filenames: false
        always_run: true
      - id: check-settings
        name: check for invalid settings keys
        entry: python scripts/tools/check_settings.py
        args: [--errors-only]
        language: system
        pass_filenames: false
        always_run: true
